### ISSUE TITLE
Boards could display the closed issues as well

### ISSUE THREAD

**Issue by luan-cestari** [ZenHubIO/support#92] opened 2014-07-08 20:42 UTC
Hi guys!

My team just started to use zenhub. We liked it a lot. But one thing we just noticed is the boards doent display the closed issues but in our case we would like that all the issues could be displayed on that, so we could manage the closed issues as well (like, maybe it will need a review, etc). (note: there is a "View Closed Issues" button but that move to the default github issue page) Thank you

**Comment by jperl** [comment] 2015-02-23 01:54
:+1:

**Comment by azenMatt** [comment] 2015-02-24 21:34
Hi all, 

I'm very happy to let you know that we have just shipped this feature - if you make sure you are on extension version 1.2.0 (if chrome has not auto-updated you already), then you will now be able to see your most recent 100 closed issues on the board. 

Dragging an issue into the pipeline will auto-close it and dragging a closed issue out of the pipeline to any other pipeline will re-open the issue. 

If you do not want to see the closed pipeline then you can unselect the checkbox at the top of the board to enable/disable it. 

![closed pipeline 2](https://cloud.githubusercontent.com/assets/7584089/6359620/61005c9e-bc29-11e4-8218-a542525b71a6.gif)


Il keep this issue open for a couple of days if anyone has any feedback for us on this, 

Enjoy! 

:beers:

**Comment by jperl** [comment] 2015-02-24 21:57
Awesome!!!!

**Comment by jperl** [comment] 2015-02-25 22:22
Ok, so I am excited about the closed pipeline -- but what would be much nicer is to be able to keep closed issues in other pipelines.

Here is our use case. We reference issue numbers in commits and the issues get closed when they are merged into our `devel` branch -- but they still need to go through other pipelines -- "QA Verification" and "Ready to Ship".

**Comment by azenMatt** [comment] 2015-02-27 00:23
thanks for the feedback @jperl - i've added that to an issue for v2 improvements for this feature :grinning: 

A question for everyone on this thread - when auto-closing an issue via the board, how useful would it be to be able to add a comment as to why you are closing it at the same time? 

Do you normally require a comment when closing an issue through GitHub? or do you feel it is self-evident why they are being closed?



I'm going to close this issue now we have the feature live - but please keep the feedback coming!

**Closed** 2015-02-27 00:23 UTC
Labels: Enhancement, Feature

**Comment by fredguth** [comment] 2017-06-14 13:13
@azenMatt Answering your question: I would like to have a select where I could say how I closed: fixed, won't fix, duplicated, etc which would also apply a label.

Still on the closed issues.  The problem I see is that Zenhub board is for all your issues and not by sprint.  I only want to see the current sprint issues in the board. So, I create a Milestone per sprint and move to the board only the issues in the Milestone.

The problem is with closed issues. The "Done" pipeline need to keep the issues open.  If I use the "Closed" pipeline, it show all issues closed from ever.

I wanted the done to be meaning "closed during this sprint".  Is there a way to hack this?
