### ISSUE TITLE
Cannot connect issue to PR after the PR has been merged

### ISSUE THREAD

**Issue by mrnnn** [ZenHubIO/support#1102] opened 2017-04-28 09:08 UTC
Yep, fully aware that this is not the right order of things in life, but it'd be nice if it were still possible. However, I feel like this was a thought through decision not to allow it. In that case, feel free to close this issue :-).

**Comment by kendramoroz** [comment] 2017-05-11 21:21
@mrnnn thanks for getting in touch with us! You should be able to connect a PR once merged to an issue using the UI from the PR page as long as you have the appropriate write permissions for the repo 🎉 

![image](https://cloud.githubusercontent.com/assets/11036230/25972491/0d68bdee-3655-11e7-975f-dd39fdcc3c13.png)

Once connected, the PR will be nested under the issue with the closed symbol on it, indicating that it's been merged. 

![image](https://cloud.githubusercontent.com/assets/11036230/25972474/fe667bba-3654-11e7-95c6-f98009708add.png)


If you're not seeing the connection option on a merged PR and or it's not connecting once merged let me know more about the repo/issue ID and we'll dig deeper 👍 . Feel free to send that info to support@zenhub.com if you'd like to keep it private :). 

Happy to answer any other questions you may have!

**Comment by arist0tl3** [comment] 2017-05-13 00:30
Just reported this to support but should have known to search here first =/

I'm able to connect the issues successfully pre-merge, but post-merge I hit the following errors:

![image](https://cloud.githubusercontent.com/assets/9328541/26020828/7262d8b8-3738-11e7-8f54-3bc86da58980.png)

![image](https://cloud.githubusercontent.com/assets/9328541/26020833/80ad7522-3738-11e7-90bc-aac36461d949.png)

The UI appears as expected, and I'm able to search the dropdown for the issues, the errors above happen onclick.

Chrome Version 58.0.3029.96 (64-bit)
Ubuntu 15.04

**Comment by kendramoroz** [comment] 2017-05-15 18:40
@arist0tl3 Just got back to you via email a few moments ago, but based on the screenshot scared, it looks like there might be a permission error. Can you confirm that you have write access to the repo where the issue you are attempting to connect is located?

**Comment by arist0tl3** [comment] 2017-05-15 22:43
@kendramoroz I can confirm that this is not the problem. I even tried removing myself and adding back and that didn't solve the issue. Also, I've been able to successfully link pre-merge PRs to the issues. It's only before they are created (which I understand doesn't work per your email response) and after they are merged where I am unable to link the issues.

**Comment by kendramoroz** [comment] 2017-05-16 00:12
@arist0tl3 one more quick question here—Is the issue closed? If you have even  closes issuenumber and merge the PR, it'll auto-close the issue meaning it's no longer linkable!

**Comment by arist0tl3** [comment] 2017-05-16 00:27
No, I can also confirm that closed issues don't even show up in the drop-down, so that isn't the case. 

I'll have a few PRs coming through in the next day or two and will try to do a video of the issue for you.

**Comment by kendramoroz** [comment] 2017-05-16 19:02
@arist0tl3 sounds good! One thing to keep in mind is if the PR description has `closes X` in it, it's going to prevent a post-merge to that issue since it closes it (from my earlier comment). 

Let me know what you discover :). I've re-opened this and will continue to debug on my end as well!

**Comment by arist0tl3** [comment] 2017-07-28 07:14
@kendramoroz Hey, just wondering if there has been any traction on this. Just ran into it again today. Merged a PR and was again unable to attach an issue from another board. Still see the exact same console error as before.

Ubuntu 16.04
Chrome 60.0.3112.78 (Official Build) (64-bit)

**Comment by kendramoroz** [comment] 2017-08-01 18:20
@arist0tl3 thanks for checking in! Circling back through the original conversation we were having, can you confirm the Issue that you're attempting to connect to is still open? Or has that Issue been closed (either via a comment that the PR being merged closes/resolves the Issue, or through the UI itself)

**Comment by arist0tl3** [comment] 2017-08-02 04:52
@kendramoroz 

Thanks for the quick response!

Yes, I can confirm that these issues are still open. We have two repos -- a product repo, where we track issues (that the whole team has access to) and a main repo, where the code lives (and only devs and owners have access). 

A simplified flow looks like this:

1. QA/Owner creates an issue on our Product Repo
2. Issue moves to In Progress on our Product Repo
3. Dev writes code and creates a PR on our Main Repo
4. QA moves issue to Approved on our Product Repo
5. Dev attaches PR on the Main Repo to the issue on the Product Repo
6. Dev merges PR
7. We deploy merged PRs to our live server
8. QA confirms the code is deployed and closes the issue on the Product Repo

If the dev merges the PR _before_ attaching the issue, then we still encounter the same issue. We don't actually close issues on our Product Repo until we deploy to production, so those issues are always open when the PRs are being created and merged.

Let me know if there is more information I can provide to help you with!

**Comment by kendramoroz** [comment] 2017-08-02 22:02
@arist0tl3 thanks for the thorough process notes here! Sounds like there might be something related to permissions and access so we'll re-create the same workspace that you have with permissions to debug. One last final question: Is it both devs and owners that cannot connect the PR after it has been merged? Based on the permissions you've described, only devs should be able to make the connection since they have write access to both workspaces, but I just want to confirm that is the same behaviour you're expecting to see.

**Comment by arist0tl3** [comment] 2017-08-03 00:11
@kendramoroz No problem. I'm actually the owner of both repos and am the one who initially encountered the error. I can have one of the other team members confirm a failure if they don't have access to both repos, but my expectation would be that as the owner of both repos, I wouldn't have any permissions issues.

**Comment by joycelee11** [comment] 2018-01-29 17:29
Curious if this issue was ever pinned down? Just tried to connect a merged PR with an open issue in another repo (I have write access to both repos). After choosing the issue to connect to, the button spins/loads and nothing happens. Console errors below:
![image](https://user-images.githubusercontent.com/21238967/35524496-b95b1d00-055c-11e8-81f2-b7d028905b2c.png)

**Comment by kendramoroz** [comment] 2018-01-29 19:55
😬  Thanks for bumping this one - I'm looping in our tech team to take a look. I'll be back in touch shortly with more info!

**Comment by kendramoroz** [comment] 2018-06-26 01:34
Hey everyone - recognize it's been a while on this one. Doing some cleaning and wanted to follow-up. Majority of the issues with this have been since solved, but if anyone is still experiencing this please ping us at support@zenhub.com with more details and we'll take a look!

**Closed by kendramoroz** 2018-06-26 01:34 UTC
Labels: ZenHub Support is Investigating!
