### ISSUE TITLE
Velocity is double expected value

### ISSUE THREAD

**Issue by ben3005** [ZenHubIO/support#1305] opened 2017-11-22 12:06 UTC
Our velocity report is showing double the amount of story points that have been actually achieved per sprint:

### Velocity
![image](https://user-images.githubusercontent.com/2751508/33126570-e1daa41e-cf7c-11e7-8538-2254ec7f9730.png)

### Sprint
![image](https://user-images.githubusercontent.com/2751508/33126649-25989314-cf7d-11e7-94d9-ad2611566b76.png)

It is also worth noting that the sprint has `1 Open` but there are no open cases in the sprint:
![image](https://user-images.githubusercontent.com/2751508/33126716-6a5af80c-cf7d-11e7-8545-4fdaf0b3bc64.png)

This is happening for all sprints, including the current open sprint

**Comment by big-guy** [comment] 2017-11-22 20:45
I'm seeing this as well: https://github.com/gradle/gradle-native/milestones#reports?report=velocity

I see it listing "2 repos", which are actually the same:
![image](https://user-images.githubusercontent.com/5387972/33149040-22fc497e-cf9c-11e7-9b6a-11a1903fbe09.png)

**Comment by kendramoroz** [comment] 2017-11-22 20:54
Oops! 😅 

🐛 on the loose here .. @pnavarrc on our development team is looking into it. We'll report back shortly!

**Comment by pnavarrc** [comment] 2017-11-23 00:23
Thanks for reporting these bugs! We just pushed a fix for the double-counting of story points and for the tooltip for multi-repo milestones, the Velocity Report should have the correct information now.

The bug on the number of open issues in a milestone is GitHub’s (you can confirm by temporarily disabling the ZenHub extension and reloading the milestone page), I couldn't reproduce it myself, but I remember having seen it before. Let us know if you encounter further issues!

cc @ben3005 @big-guy

**Comment by ben3005** [comment] 2017-11-23 01:56
@pnavarrc excellent, looks good on my end 👍

**Comment by big-guy** [comment] 2017-11-23 02:35
👍 LGTM

**Comment by kendramoroz** [comment] 2017-11-23 21:43
🎉  thanks all! If you have anything else that comes up you know where to drop us a line 💃

**Closed by kendramoroz** 2017-11-23 21:43 UTC
Labels: Bug
