### ISSUE TITLE
In-board creation of issues prone to loss

### ISSUE THREAD

**Issue by dhaltmayer** [ZenHubIO/support#1025] opened 2017-01-27 09:19 UTC
When creating an issue from the board view, accidentally clicking outside of the modal will lead to a loss of the issue. Maybe there could be some kind of warning, if the board view issue modal is up and any edits have been made, before dismissing the modal.

**Comment by kendramoroz** [comment] 2017-01-27 17:45
@dhaltmayer Thanks for sending this our way! The issue modal should be saving your text, similar to GitHub's behaviour—looks like you captured a 🐛  here! I'll spin up an issue to get this tackled by our dev team.

**Comment by mnapoli** [comment] 2017-02-17 10:41
Happened to me too and I realized that only a few days later, it's really surprising!

**Comment by kendramoroz** [comment] 2017-02-17 23:26
@mnapoli is the text being lost still? Should be all fixed now so let us know if it's still happening!  
🔥 🚒

**Comment by mnapoli** [comment] 2017-02-19 19:57
Well the problem is that you can leave the tab or close the window because you think the issue is created. It's not really a bug to me but rather a usability issue: it should be very explicit that the issue is not created (e.g. a modal or anything else).

**Comment by kendramoroz** [comment] 2017-02-20 01:55
@mnapoli great point! I'm 🚢 this off to our design team as feedback on how we can make the board experience better for our users.

**Closed** 2017-03-17 21:03 UTC
Labels: Bug, Launched!
