### ISSUE TITLE
ZenHub Chrome Extension mess up organization page

### ISSUE THREAD

**Issue by kj415j45** [ZenHubIO/support#1527] opened 2018-09-28 14:59 UTC
ZenHub Extenstion disable:
![image](https://user-images.githubusercontent.com/18349191/46216355-f55c7c80-c371-11e8-99c9-71bfc4d6e1dd.png)

ZenHub Extension enable:
![image](https://user-images.githubusercontent.com/18349191/46216394-0f965a80-c372-11e8-8d05-5c0dd162cd44.png)

I'm not sure what happened

ZenHub Extension: 2.37.87
Chrome: 69.0.3497.100

**Comment by kendramoroz** [comment] 2018-09-28 17:03
Thanks for reporting! We are working on a fix 🔥

**Comment by devinmcinnis** [comment] 2018-09-28 19:52
Fixed on the latest version of the extension.

Duplicate of #1526

**Closed by devinmcinnis** 2018-09-28 19:52 UTC
Labels: Bug
