### ISSUE TITLE
BUG: Can't select issues that are closed.

### ISSUE THREAD

**Issue by bmunkholm** [ZenHubIO/support#1255] opened 2017-09-26 16:36 UTC
As a user I would like to slect mulitple closed issues and be able to set various thing like labels, epics, releases etc. Some times it was forgotten to set certain properties before the issue was closed.

**Comment by adamreisnz** [comment] 2017-09-27 03:31
This appears to be a duplicate of my issue, https://github.com/ZenHubIO/support/issues/999

The funny thing is, I just experienced this pain again, and wanted to follow up to see what's happening with it, and then I see your issue at the top of the list. Good timing.

@azenMatt are you guys looking into this? It's really a pain not to be able to select closed issues for multi actions. I just wanted to move a bunch of issues from a certain milestone to a new one. Can't do it, have to do them 1 by 1... 😢

**Comment by kendramoroz** [comment] 2017-10-04 19:26
Thanks for reporting @bmunkholm! As @adamreisnz mentioned, #999 addresses this so I'll close this one to ensure everyone can stay in sync with the thread on #999. 

No immediate updates to provide on this, but on our radar as a potential future enhancement. Stay tuned to 999 for more updates - we'll be sure to post them as they become available!

**Closed by kendramoroz** 2017-10-04 19:26 UTC
