### ISSUE TITLE
Set Estimate API converting floats to integers

### ISSUE THREAD

**Issue by clickthisnick** [ZenHubIO/support#1187] opened 2017-07-17 18:28 UTC
I'm using this API:
https://github.com/ZenHubIO/API#set-estimate-for-issue

Seems like whatever you pass in for the estimate value gets cast from a float to an integer.

Example Tests Cases:

---

Test 1:
`{ "estimate":1}`

Result:
estimate set to 1 -> Correct!

---

Test 2:
`{ "estimate":5.25}`

Result:
estimate set to 5 -> Wrong! Where did .25 go?

---

Test 3:
`{ "estimate":0.5}`

Result:
estimate set to 0 -> Wrong! Where did .5 go?

---

Q: But clickthisnick why are you not using fibonacci?
A: Zenhub allows 0.5 via the `https://api.zenhub.io/v2/honestbuildings/api/issues/x/estimates` endpoint. Please make it work for the api too!

**Comment by clickthisnick** [comment] 2017-07-24 18:20
@kendramoroz Here is another issue relating to this:
https://github.com/ZenHubIO/support/issues/1194

Please don't take that functionality away! Def needed for many teams!

**Comment by kendramoroz** [comment] 2017-07-24 18:22
@clickthisnick just left a comment on #1194! Let me know if it doesn't work for you. 
I'll have the team dig into the API issue here, but the creation of the new estimate in the UI should be fixed with the 0!

**Comment by kendramoroz** [comment] 2017-07-24 18:28
@clickthisnick confirmed to be a 🐛 ! Issuing up for a fix with the team.

**Comment by clickthisnick** [comment] 2017-07-25 22:13
@kendramoroz Thanks appreciate it!

**Comment by kendramoroz** [comment] 2017-08-04 19:55
Hey @clickthisnick We launched a fix for this bug on the API :). Let me know if you're still noticing any issues!

**Comment by TobyAbel** [comment] 2017-08-16 07:51
Hey, I think this may have caused a regression elsewhere ;)

![screen shot 2017-08-16 at 08 50 20](https://user-images.githubusercontent.com/922475/29352826-1c357432-8260-11e7-92e1-f9af81044405.png)

**Comment by kendramoroz** [comment] 2017-08-16 21:06
@TobyAbel thanks for reporting this! Looks like it's not related to the API update, but definitely a regression in other recent bug fixes. I'll have our team take care of this one 👍

**Closed** 2017-09-06 17:34 UTC
Labels: API, Bug, Launched!
