### ISSUE TITLE
Not able to open board

### ISSUE THREAD

**Issue by petrmm** [ZenHubIO/support#720] opened 2016-05-06 07:55 UTC
When I try to open board, loading stops in state bellow.
![image](https://cloud.githubusercontent.com/assets/7623513/15067299/90a92df6-136f-11e6-83f2-28ed3d293560.png)

In JS console is error:
WebSocket connection to 'wss://api.zenhub.io/socket.io/?token=***&EIO=2&transport=websocket' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1
main.js:12

I tried to reinstall crome extension, remove cookies, but nothing helps.

Can you help what to do? Thank you for answer.

**Comment by henryoswald** [comment] 2016-05-06 13:49
Are you on windows?

**Comment by petrmm** [comment] 2016-05-06 13:52
Windows 10, browser Chrome 50.0.2661.94 m

**Comment by petrmm** [comment] 2016-05-06 13:58
I'm not sure, but I thing it worked til the latest update Chrome browser.

**Comment by azenMatt** [comment] 2016-05-07 00:41
Hi @petrmm - we are taking a look into this - it does seem to be impacting a number of people

**Comment by ctu-lshtm** [comment] 2016-05-09 10:50
My colleague has this problem.  Maybe adblcoker?  I don't have an adblocker on my Chrome, but he has.  We tried disabling it (but no uninstalling it), still doesn't work.

**Comment by zhangchiqing** [comment] 2016-05-09 19:10
Hi @petrmm , did you install any new chrome extension recently (other than ZenHub chrome extension)?

Could you try creating a new chrome profile, install the ZenHub chrome extension and then open the board? 

Thanks

**Comment by henryoswald** [comment] 2016-05-09 19:13
We've had reports from other sources that this is caused by "ESET Smart Security". I'm not 100% sure what this does, but there are instructions for uninstalling it at http://support.eset.com/kb2289. Do you have this installed, and does it work if you uninstall/disable it?

​

**Comment by adamteece** [comment] 2016-05-09 20:45
@zhangchiqing I tried out the new profile with nothing but the ZenHub extension and was still blocked. I do have ESET Nod32 Antivirus though and that is the virus scanner I use. I am not sure why that would break it, and I am not getting any alerts from Nod32 as to why it would be blocking it.

**Comment by zhangchiqing** [comment] 2016-05-09 20:53
@adamteece Thanks for trying. So we can exclude the impact from other extensions. 

Could you also do a websocket Echo Test? Please follow these steps:

1. Go to http://www.websocket.org/echo.html
2. Click "Use secure WebSocket (TLS)"
3. Click "Connect"
4. Click "Send"

Do you see the same output as mine?

![screenshot 2016-05-09 13 52 18](https://cloud.githubusercontent.com/assets/811374/15127837/48d52da6-15ed-11e6-93ca-40a84c483985.png)

**Comment by adamteece** [comment] 2016-05-09 20:57
@zhangchiqing that seemed to work fine - http://d.pr/i/1itWt/3JF6jIAB

**Comment by petrmm** [comment] 2016-05-09 21:14
@henryoswald it is good advice, several days later I updated Eset SmartSecurity from version 8 to 9. I can't try it now. Tomorow I will try uninstall Eset and test if it causes the problem.

**Comment by zhangchiqing** [comment] 2016-05-09 21:30
Thanks again @adamteece . Looks like the websocket works fine in your browser.

Could you try the echo test with ZenHub API? Please follow these steps:

1. Go to http://www.websocket.org/echo.html 
2. Click "Use secure WebSocket (TLS)"
3. Put the following url into the Location field
wss://api.zenhub.io/socket.io/?token=123&EIO=2&transport=websocket
4. Click "Connect"

Do you see the same output? If not, is there any error in your console?
![screenshot 2016-05-09 14 28 36](https://cloud.githubusercontent.com/assets/811374/15128711/57db58a2-15f2-11e6-8459-c5900170222d.png)

**Comment by adamteece** [comment] 2016-05-09 21:31
@zhangchiqing Here is what I get when I try to connect to that -  

 CONNECTED

 ERROR: undefined

 DISCONNECTED

**Comment by zhangchiqing** [comment] 2016-05-09 21:36
OK, Thanks @adamteece .

Could you open your chrome dev console and check if there was any error? What is the error message for that request?

![screenshot 2016-05-09 14 34 10](https://cloud.githubusercontent.com/assets/811374/15128876/203ca1b6-15f3-11e6-8cb8-50419aa6be5e.png)

**Comment by adamteece** [comment] 2016-05-09 21:43
Request URL:wss://api.zenhub.io/socket.io/?token=123&EIO=2&transport=websocket&encoding=text
Request Method:GET
Status Code:101 Switching Protocols
Response Headers
view source
Connection:upgrade
Date:Mon, 09 May 2016 21:41:34 GMT
Sec-WebSocket-Accept:UxyaU652qaxpGH96oOeLlbxuCqw=
Server:nginx
Transfer-Encoding:chunked
Upgrade:websocket
Request Headers
view source
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:Upgrade
Cookie:optimizelyEndUserId=oeu1462826482639r0.39806417660240867; optimizelySegments=%7B%225203912312%22%3A%22false%22%2C%225203901146%22%3A%22direct%22%2C%225210851715%22%3A%22gc%22%7D; optimizelyBuckets=%7B%7D; _ga=GA1.2.1955946006.1462826484; mp_28eacd763239e0137e163cc1da830f90_mixpanel=%7B%22distinct_id%22%3A%20%221549740bf981b0-002a39a12342a3-78153b-1fa400-1549740bf9a2bc%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; mp_mixpanel__c=0; mp_mixpanel__c3=0; mp_mixpanel__c4=0; mp_mixpanel__c5=0; connect.sid=s%3AiDp2cGaEgYCwdh0OZZez8CwE.4OdZcsCceM%2FVGk3nozcUPkRlFE4BDDG%2FepTEYPitNHw
Host:api.zenhub.io
Origin:http://www.websocket.org
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:F5RfaqyO3CKyAHStG9Qh2w==
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
Query String Parameters
view source
view URL encoded
token:123
EIO:2
transport:websocket
encoding:text

And then on Frames I see

 (Opcode -1)

Wondering if this issue is more wide-spread https://github.com/socketio/socket.io/issues/412 but for some reason that issue is closed?

**Comment by zhangchiqing** [comment] 2016-05-09 22:06
@adamteece To check if it's caused by your anti-virus program, could you turn it off temporarily and try again?

**Comment by adamteece** [comment] 2016-05-09 23:16
I disabled it as seen in this screenshot http://d.pr/f/1fwOn/3mSs1vL1 but still getting the same error. Even after restarting Chrome.

**Comment by zhangchiqing** [comment] 2016-05-10 00:59
Hi @adamteece , could you follow [this post](https://github.com/socketio/socket.io/issues/2543#issuecomment-218010922) to check if it works for you? They had the same issue and the same anti-virus program installed.

>So I searched again and found this site Link which was actually a forum that seems like it is russian or something similar and translated that via google translate. Then I found the issue for me. I use eset nod32 antivirus software and there is also an option for filtering web protocols.
As described in the forum post I deactivated the following setting. Right-click on the tray icon -> advanced settings -> Internet & Email (or Web & Email) -> And then deactivate the checkbox "Check application specific protocols".

**Comment by adamteece** [comment] 2016-05-10 02:30
@zhangchiqing That fixed it. So what can we do so that my Antivirus isn't yelling at me about not being fully protected and still make this work?

**Comment by adamteece** [comment] 2016-05-10 02:38
I did some further testing. I don't have to turn off the entire web filtering, but just the SSL/TLS part it seems - http://d.pr/i/1hh0j/4O6ERpLZ When I just disable that it started to work and Nod32 is less angry with me.

**Comment by adamteece** [comment] 2016-05-10 02:52
Ok I did some more testing and have a decently safe workaround. Still not ideal but it works for now - http://screencast-o-matic.com/watch/cDh6ns1PFM video on how to fix it.

**Comment by zhangchiqing** [comment] 2016-05-10 03:25
Cool! @adamteece Thanks for sharing the safe workaround and helping the debugging. 

I will close this issue for now.

**Closed by zhangchiqing** 2016-05-10 03:25 UTC
