### ISSUE TITLE
Board loading hangs on "We are loading your issues" for repositories having no issues

### ISSUE THREAD

**Issue by cbeams** [ZenHubIO/support#675] opened 2016-04-12 04:02 UTC
Repro steps:

1. Create a new GitHub repository
2. Click "Boards"
3. Notice that the UI hangs on the "We are loading your issues..." screen
4. Click "Issues and add one.
5. Click "Boards" again.
6. Notice that the UI proceeds to load as expected.

**Comment by azenMatt** [comment] 2016-04-12 05:11
Thanks for reporting this @cbeams - we will add in better error handling to support the 'no issues' case 👍

**Comment by Mottie** [comment] 2016-04-12 15:59
Duplicate of #650.

**Comment by azenMatt** [comment] 2016-04-12 16:03
2.16.25 has just been released that shows an empty board for this situation 😄

**Closed by azenMatt** 2016-04-12 16:03 UTC
Labels: confirmed

**Comment by cbeams** [comment] 2016-04-13 04:05
> 2.16.25 has just been released that shows an empty board for this situation 😄

Confirmed on my side, thanks @azenMatt. /cc @pioterj

As an aside, it looks like there's an issue rendering the `Closed` column in a zero-issue environment. I see the following—note the thin vertical line where the `Closed` column should be:

![image](https://cloud.githubusercontent.com/assets/301810/14482500/9f6f6420-013d-11e6-8b5d-11cf3fd8910b.png)

**Comment by azenMatt** [comment] 2016-04-14 01:30
thanks for confirming. 

we will ad the closed column problem to the backlog - appears to be a non-impacting issue though (as no issues to see anyway!) so il mark it as low priority
