### ISSUE TITLE
Convert a GitHub Issue Into a Pull Request

### ISSUE THREAD

**Issue by hadrienl** [ZenHubIO/support#275] opened 2015-06-26 06:52 UTC
With a button into the issue which will ask for the base branch and the target branch [acting like `hub` command](http://opensoul.org/2012/11/09/convert-a-github-issue-into-a-pull-request/).

**Comment by nicoolas25** [comment] 2015-06-26 07:39
+1

**Comment by DirtyF** [comment] 2015-06-28 23:22
> Issue to pull request conversion via -i <ISSUE> or ISSUE-URL arguments is deprecated and will likely be removed from the future versions of both hub and GitHub API.

source : https://hub.github.com/hub.1.html

**Comment by hadrienl** [comment] 2015-06-29 07:16
Shit :/

**Comment by aupright** [comment] 2015-07-09 05:25
Hey @hadrienl and @DirtyF thanks for the discussion here!

Based on the documentation provided above, I'm going to move this one here into the community icebox as something to look at going forward. Let's continue to keep an eye on things with the GitHub API as there may be an opportunity to re-visit this again in the future.

**Comment by m-roberts** [comment] 2016-04-25 18:05
Isn't this a duplicate of #17 ?

**Comment by kendramoroz** [comment] 2017-09-08 18:54
👋  Hey everyone - closing this Issue as GitHub's deprecated native support for the conversion of Issues to PRs. Feel free to reach out to support@zenhub.com with any questions!

**Closed by kendramoroz** 2017-09-08 18:54 UTC
Labels: Low Priority, Reference
