### ISSUE TITLE
As a developer, I want to be able to sort the issues in the boards by newest

### ISSUE THREAD

**Issue by shehzan10** [ZenHubIO/support#348] opened 2015-08-18 20:14 UTC
Right now the default and only was is sorted oldest opened (top) to newest opened (bottom). There are many cases where newest on top is more useful.

**Comment by aupright** [comment] 2015-09-02 04:47
Thanks for the feedback @shehzan10 - it looks live there are a few other votes for this functionality as well. As part of our near-term product roadmap, we're exploring a number of different improvements that we can make to our boards view. I'll keep this one open in the discussion pipeline to see if we can get a few more comments and +1's from the community :smiley:

**Comment by Mottie** [comment] 2016-03-19 18:12
I created a userscript which adds sort arrows to the pipeline header... check it out here: https://github.com/Mottie/ZenHub-userscripts

![zenhub-sort-issues](https://cloud.githubusercontent.com/assets/136959/13900020/3d5e1c94-edca-11e5-821e-c9665a66458f.gif)

**Comment by Mottie** [comment] 2016-03-26 17:45
I just updated the [sort userscript](https://github.com/Mottie/ZenHub-userscripts), you can now select what you want to sort on:

![zenhub-sort-issues](https://cloud.githubusercontent.com/assets/136959/14061332/ec60109a-f34b-11e5-8ae8-118ab64a45a8.gif)

**Comment by aupright** [comment] 2016-03-26 18:14
@Mottie :heart_eyes:

**Comment by basdek** [comment] 2016-04-18 14:53
@Mottie Your solution is not working for me (using latest firefox and latest chrome on linux)

**Comment by Mottie** [comment] 2016-04-18 15:19
@basdek, I just noticed that the assignee HTML layout has changed. Also, it appears that tinysort's secondary sort isn't working as intended, so I'll remove that for now. Expect an update in a few minutes.

**Comment by basdek** [comment] 2016-04-18 15:20
@Mottie Super awesome :+1:

**Comment by azenMatt** [comment] 2016-04-19 01:03
@Mottie - I don't think we have sent you any ZenHub swag? We've got to get you rocking some ZenHub t-shirts 😀 . If you can send me an email to our support address (support@zenhub.io) we can send some over!

**Comment by payammeyer** [comment] 2016-05-03 13:32
Thanks so much @Mottie !

**Comment by payammeyer** [comment] 2016-05-03 13:38
One comment, is there any way to keep the sort after edits? As soon as I edit an issue in a pipeline, the sort goes back to oldest at the top. Not a huge deal to push the button again but a little annoying.

**Comment by Mottie** [comment] 2016-05-03 21:29
@payammeyer I'll see what I can do when I get some free time :grin:

**Comment by payammeyer** [comment] 2016-05-03 21:30
Haha I know, sorry, don't mean to be nit picky, I appreciate it.

**Comment by Mottie** [comment] 2016-05-04 00:05
@payammeyer Umm, ok. I don't think I can get it to work....There is no easy way to figure out when all the issues have finished loading. For example, the [odoo repo](https://github.com/odoo/odoo#boards) currently has 3,331 issues. It takes about a minute to finish loading them all into the ZenHub boards thanks to asynchronous adding of DOM nodes. You can apply a sort during that loading, but it won't be a complete sort.

**Comment by azenMatt** [comment] 2016-05-04 00:12
> For example, the odoo repo currently has 3,331 issues. It takes about a minute to finish loading them all into the ZenHub boards thanks to asynchronous adding of DOM nodes. You can apply a sort during that loading, but it won't be a complete sort

If it helps - we are working on making that faster :)

**Comment by azenMatt** [comment] 2016-05-04 00:13
Also, as a heads up @Mottie  - we are going to get rid of that hover effect on the pipeline name as we have had a number of complaints for it recently. Is that going to impact the functionality you have here?

**Comment by Mottie** [comment] 2016-05-04 00:14
LOL, I know you guys are doing awesome!

Hmm, I guess I could compare the pipeline issue count to the number of issues...

> we are going to get rid of that hover effect on the pipeline name

Yeah, I just need to some css. No biggie.

**Comment by payammeyer** [comment] 2016-05-04 11:10
@Mottie thanks for looking into it anyways.

**Comment by azenMatt** [comment] 2016-05-04 23:39
:) that hover update is live on the latest extension

**Comment by ambynair** [comment] 2016-05-07 23:19
@Mottie How doest the sorting work for zenhub enterprise ? is there a setting / code changes I can make to work for zenhub enterprise ?

**Comment by Mottie** [comment] 2016-05-07 23:47
Hi @ambynair! 

Whatever userscript plugin/extension you're using should allow you to edit the userscript. Open the editor and add a line (around line 7) that includes your enterprise URL:

```js
// @include https://github-enterprise.dev/*
```

Sadly, you'll need to do this every time the userscript updates, so you might also want to remove these lines to prevent it:

```js
// @updateURL     https://raw.githubusercontent.com/Mottie/Zenhub-userscripts/master/zenhub-sort-issues.user.js
// @downloadURL   https://raw.githubusercontent.com/Mottie/Zenhub-userscripts/master/zenhub-sort-issues.user.js
```

**Comment by ambynair** [comment] 2016-05-07 23:53
@Mottie  I did that. before i even tried to add it via externals. neither seems to be working. 
I have attached screenshot : both scripts are running , I dont see the toggle icon as well.
I am guessing there is some setting that I need to change to enterprise url.

<img width="1659" alt="screen shot 2016-05-07 at 4 51 01 pm" src="https://cloud.githubusercontent.com/assets/10192159/15095283/f5b8debc-1473-11e6-893d-bed3c3889ddb.png">

Appreciate your help.

**Comment by Mottie** [comment] 2016-05-08 00:03
Would you please [open an issue](https://github.com/Mottie/ZenHub-userscripts/issues) so we can continue this discussion there. I don't want to fill this issue with comments on non-related stuff.

**Comment by ambynair** [comment] 2016-05-12 16:09
How can show  "Created date" on the issue card on zenhub board ?

**Comment by azenMatt** [comment] 2016-12-14 20:04
This is currently live on ZenHub.com and will be in the January Enterprise release :)

**Closed by azenMatt** 2016-12-14 20:04 UTC
Labels: Enhancement, needsVotes

**Comment by payammeyer** [comment] 2016-12-14 20:52
Yep, love it.
