### ISSUE TITLE
allow access for external users

### ISSUE THREAD

**Issue by sakulstra** [ZenHubIO/support#1445] opened 2018-05-30 12:29 UTC
Our current workflow while using trello is, to have a big "developers board"(only developers), a "feature discussion board"(all) and a "stakeholders/support board"(support team).
We then use tags within the developers board to sync tickets with the stakeholders board.

I guess sth similar will be possible with #139 but as I get it zenhub is currently only usable via a github account. Which is fine for us developers, but sadly a blocker as we had to get stakeholders and support team members on github and don't even have an option to restrict repo access.

**Comment by kendramoroz** [comment] 2018-06-06 00:10
Agreed this is a great idea! Currently there's no immediate upcoming announcements in the roadmap to offer a non-github account connection to ZenHub, but we 💯 see the value and want to go in that direction as we grow the product. As this is a duplicate of #178 I'm going to close to try consolidate issues, so please feel free to subscribe there for future updates!

**Closed by kendramoroz** 2018-06-06 00:10 UTC
