### ISSUE TITLE
An error occurred while loading epic for the epic creator

### ISSUE THREAD

**Issue by mgenev** [ZenHubIO/support#741] opened 2016-05-18 07:13 UTC
I'd love to use ZenHub, but when I try to create an Epic, I get:
`An error occurred while loading epic for the epic creator` in a dialog box 

and then I get taken out of the epic creator.

Please help

**Comment by azenMatt** [comment] 2016-05-18 17:13
Hi @mgenev, 

a couple of questions on this.... 

1) Do you have write access to the repo where you are trying to create the epic?

2) Do you get any errors in the developer console when trying to access this? (On chrome, you can get these via view -> developer -> javascript console -> errors) A screenshot of these would be very helpful to get this working for you!

**Comment by Lilyheart** [comment] 2016-08-09 02:25
I am having this same problem.

It occurs on a private repo where I am the only one with access.  It did not occur on a rep of mine that is public.

I do receive a console error.  `Failed to load resource: the server responded with a status of 500 (Internal Server Error)  https://api.zenhub.io/v4/repositories/65209726/issues/epics-estimates?forceUpdate=1`

**Comment by azenMatt** [comment] 2016-08-09 21:24
Thank you for the update @Lilyheart - please let me know if this starts to occur again

Il pass the error message onto the team, but it looks like this might be a server issue on ourside which would explain why it is not reproducible

**Comment by dbansch** [comment] 2016-09-16 16:21
I'm having the same problem.  I created an empty repo and tried to create and Epic.  I clicked "Issues", entered a title, and clicked "Create an Epic".  I get a very similar screen as @Lilyheart.  I tried to added a collaborator to the repo an tried again, but I had the same result.

**Comment by azenMatt** [comment] 2016-09-16 19:48
Hi @dbansch - would you be able to confirm which version of the extension you are on? And provide a screen shot of any errors in your browsers developer console that appear as you try and open this?

**Comment by dbansch** [comment] 2016-09-19 14:47
I'm using Zenhub Enterprise 2.7.3.  

![76ca2be2b2c2d48d](https://cloud.githubusercontent.com/assets/6922791/18636313/e8293046-7e4d-11e6-89fe-7e0a2e245dce.jpg)

**Comment by azenMatt** [comment] 2016-09-20 18:26
Do you have any other browser extensions loaded that might be blocking this? For example, Privacy Badger is one that users often have problems with. 

also - it is just the epics screen you get this with, or also when opening a board?

**Comment by dbansch** [comment] 2016-09-20 18:53
I don't have Privacy Badger.  I can't get to the Boards or Burndowns tabs to load.  I think it might be an issue with my firefox installation.  I switched to Chrome and everything seems to work.

**Comment by azenMatt** [comment] 2016-09-20 20:38
It would be worth trying it with a clean Firefox profile - that would confirm if it is a browser issue

**Comment by kendramoroz** [comment] 2017-01-27 06:40
@mgenev @Lilyheart @dbansch Hey Zenhubbers! Kendra here from ZenHub team, doing some spring cleaning of our support boards 🌷 — Are you still experiencing any issues with epics that I can follow-up on? If I don't hear back, I'll close the issue here but feel free to create a new issue if anything comes up moving forward. Happy weekend 🚀

**Closed** 2017-02-22 22:15 UTC
Labels: ZenHub Support is Investigating!
