### ISSUE TITLE
Avatar & title error

### ISSUE THREAD

**Issue by OxGroup** [ZenHubIO/support#728] opened 2016-05-10 10:59 UTC
It is not clear what he was guided by
It is best to then use an **avatar** who **created the query** as it is implemented in github
![img 1](http://dl2.joxi.net/drive/2016/05/10/0011/3997/786333/33/f8a0f8c10d.jpg)
![img 2](http://dl1.joxi.net/drive/2016/05/10/0011/3997/786333/33/bfaa37e09e.jpg)
It is best to then use an avatar who created the query as it is implemented in github

Also, the **name of the repository** in the list is useless, because it's obvious. It is better to write a **login**
![img 3](http://dl2.joxi.net/drive/2016/05/10/0011/3997/786333/33/1900db56a1.jpg)

**Comment by OxGroup** [comment] 2016-05-10 11:24
Here it will be good
![img](http://dl2.joxi.net/drive/2016/05/10/0011/3997/786333/33/c6df1ef232.jpg)

**Comment by azenMatt** [comment] 2016-05-12 19:04
Hi @OxGroup - thanks for the feedback, 

Currently the avatar on the board is used to show who the issue is assigned to. But we have had lots of requests to also show who created the issue - and particularly to allow filtering by 'created by'

We believe that the 'assigned' user should have the most prominence on the card - as they are responsible for the next action to the card. Whereas the issue-creator may never come back to it. 

The Name of the repo exists mainly for the Multi-repo-board, where it is useful to know which repo an issues exists in. 

Il make sure this feedback gets to our design team 👍

**Comment by OxGroup** [comment] 2016-05-13 16:59
logical that the avatar to the left refers to the one who made the request. He to whom he entrusted to be right.
An example is much easier in the second message

**Comment by azenMatt** [comment] 2016-05-13 17:03
Let me reopen this and attached the 'needs votes' label - happy to make this change if we can get enough 👍    😄

**Comment by OxGroup** [comment] 2016-05-13 18:48
Thank.
Just when I need to get a list of tasks for me that I can just set up a filter "Filter Issues by assignee".

A blank space is also occupied by avatars are not interested. This place is more logical to fill the avatar who created the request. or even remove it from there and move to the right.

**Comment by alexamorozov** [comment] 2016-05-14 10:43
+

**Closed** 2018-01-20 00:39 UTC
