### ISSUE TITLE
Sorting new issues

### ISSUE THREAD

**Issue by basdek** [ZenHubIO/support#685] opened 2016-04-18 08:03 UTC
It seems not possible to sort issues on their date of creation, their number, etc. 
This is severly annoying

**Comment by Mottie** [comment] 2016-04-18 11:57
Duplicate of #348... sorting by issue number is pretty much the same as sorting by their date of creation.

**Comment by azenMatt** [comment] 2016-04-26 21:35
Hi @basdek - this is covered by #348, if you can subscribe to that issue, we will keep you updated on progress. 👍

**Closed by azenMatt** 2016-04-26 21:35 UTC
