### ISSUE TITLE
Board view loses Assignee selection intermittently

### ISSUE THREAD

**Issue by alexchantastic** [ZenHubIO/support#222] opened 2015-05-01 16:59 UTC
Since the latest revision to the Board view with mutli-repo support, my Assignee selection has intermittently been cleared. I can't seem to reproduce this purposely, but it definitely happens quite often.

1. Navigate to a ZenHub Board view
2. Set an assignee filter
3. Wait a bit and do other things while keeping the Board view tab open
4. Observe that the previously set assignee filter has been cleared with no input from the user

**Comment by azenMatt** [comment] 2015-05-01 23:29
Hi @alexchantastic - thanks for reporting this - we are looking into it. 

Do you know if other users were creating multi-repo boards during this time?

**Comment by alexchantastic** [comment] 2015-05-01 23:31
I'm not sure, but I highly doubt it.

**Comment by azenMatt** [comment] 2015-05-05 22:28
We pushed out a backend fix for this over the weekend - I have not been able to replicate since so this should be working for you as well now. 

Please re-open if you are still getting this problem and il investigate further!

**Comment by alexchantastic** [comment] 2015-05-06 18:40
@azenMatt Yes, this still occurs for me (running ZenHub 2.0.2 on Chrome 42.0.2311.135 (64-bit)).

**Comment by azenMatt** [comment] 2015-05-06 22:25
I've been able to reproduce this consistently now. It looks like we are dropping out the filter on certain refresh events. 

we will get a fix out for this one as soon as we can!

**Comment by alexchantastic** [comment] 2015-05-20 18:47
@azenMatt any word on this bug? It's getting quite annoying and is happening more and more often now.

**Comment by azenMatt** [comment] 2015-05-20 20:39
@alexchantastic - this is high on our 'bugs to squash' list - should be a change into production for it next week.

**Comment by jirihelmich** [comment] 2015-05-26 09:27
Also experiencing this.

**Comment by azenMatt** [comment] 2015-06-02 15:57
@alexchantastic @jirihelmich - This has just been fixed in version 2.1.15 

Any other issues, please let me know!

**Closed by azenMatt** 2015-06-02 15:57 UTC

**Comment by jirihelmich** [comment] 2015-06-02 16:03
We've already noticed, thanks a lot!
