### ISSUE TITLE
Github keyboard shortcuts don't work on the boards page

### ISSUE THREAD

**Issue by shawninder** [ZenHubIO/support#328] opened 2015-07-31 12:27 UTC
Repro:

- Go to your favorite repo
- Go to _boards_ page
- Use a GitHub keyboard shortcut (like `g+i`)
- *Expected* works (goes to _issues_ page in the case of `g+i`)
- *Observed* fails (does nothing)

**Comment by aaronwest** [comment] 2015-07-31 18:42
Yep, seeing the same thing on Chrome 44.0.2403.107 on Macbook Pro.

**Comment by azenMatt** [comment] 2015-08-07 01:22
We are looking at a fix for this one :)

**Comment by toddmedema** [comment] 2015-08-21 20:58
Looks like a duplicate of https://github.com/ZenHubIO/support/issues/313

**Comment by azenMatt** [comment] 2015-08-31 20:24
Yes, this one is now also live in 2.5.16!

**Closed by azenMatt** 2015-08-31 20:24 UTC

**Comment by aaronwest** [comment] 2015-09-01 17:41
Working great. Thank you ZenHub team!
