### ISSUE TITLE
Board view breaks keyboard navigation

### ISSUE THREAD

**Issue by mjonas87** [ZenHubIO/support#313] opened 2015-07-17 20:07 UTC
https://help.github.com/articles/using-keyboard-shortcuts/
1. Open a repository and view the Zenhub board.
2. Attempt to navigate to Pull Requests by using the keyboard shortcut "g+p".
3. Observe the Issues board is still displayed, even though the correct menu item is selected on the right-hand nav bar.

**Comment by aupright** [comment] 2015-07-29 04:56
Thanks for reaching out here @mjonas87 - I've issued this one up internally so that we can take a look at putting together a fix. Based on the steps that you outlined above, it sounds like the keyboard shortcut still works as intended, but that the board modal is not being closed when you're redirected to this new page (which is likely being shown behind the board). 

I'll keep this one open in our `known issues` column and provide you with an update as soon as we're able to go live with a fix on this.

**Comment by mjonas87** [comment] 2015-07-29 17:26
Thanks! Yeah, I realized that I just needed to toggle the board with `b`. However, I think that interaction can be a bit confusing as it has the same UI weight as any of the other pages with links on the right-nav. Probably should just auto-close the board when attempting to navigate via shortcut keys to another page.

**Comment by JeanMertz** [comment] 2015-07-30 06:09
@aupright is there a way to view all the shortcuts introduced by ZenHub?

I'm very interested in using the product at our team, and evaluating its usage, but found two shortcut related issues so far:

* unclear which shortcuts are supported
* `c` is the default "create issue" shortcut in GH, but ZenHub also uses it to toggle "show closed"

**Comment by kendramoroz** [comment] 2017-01-27 06:32
@JeanMertz I know it's been a while since you asked about shortcuts, but doing some spring cleaning 🌷 and came across this! [We have more documentation on our time-saver features here](https://www.zenhub.com/documentation/streamline-my-github-workflow#keyboard-shortcuts), but I've also pasted in all the shortcuts below. 

I also noticed that the g+p issue for the board is fixed, so I'll be closing this issue, but feel free to post a new issue with any other questions or feedback! 
 
 ---

- Open Board: `b`
- Change an issue's pipeline: `p`
- Set/Change issue's estimate: `e`
- Open Burndown Chart: `d`
- Add a ToDo: `Shift z`
- Open ToDo page: `z`
- Open Rapid Repo Switcher: `f`
- View GitHub shortcuts: `?`

**Closed by kendramoroz** 2017-01-27 06:32 UTC
