### ISSUE TITLE
Urgent: impossible to open existing issues

### ISSUE THREAD

**Issue by guillaumecharles** [ZenHubIO/support#516] opened 2015-12-16 17:05 UTC
Since an hour or so, it is not possible to open issues to edit them. The screen gets stuck loading the issue:

![image](https://cloud.githubusercontent.com/assets/13978246/11847827/99e68f5e-a41f-11e5-8c00-ed3ec94fa69b.png)

**Comment by wzin** [comment] 2015-12-16 17:39
Possible duplicate of #515 :)

**Comment by azenMatt** [comment] 2015-12-16 17:53
Hi @guillaumecharles @wzin - we are working on a fix at the moment  - expect a new version very soon!

**Comment by azenMatt** [comment] 2015-12-16 18:41
v2.13.17 just went live which contains the fix for this! Your browser should push and update to you shortly, else you can manually ask it to update via the extensions page!

**Closed by azenMatt** 2015-12-16 18:41 UTC
