### ISSUE TITLE
Error when creating Milestone

### ISSUE THREAD

**Issue by JenHa** [ZenHubIO/support#1285] opened 2017-11-02 11:50 UTC
Hello there, 
When I try to create a new milestone I get the following message: "There was an error creating the milestone in *project*"
In the debugger is an error too. See in the picture I added. 
Am I doing something wrong?
![error](https://user-images.githubusercontent.com/24609663/32324626-4f4893f0-bfcc-11e7-9d8b-b2cb91cc59ad.PNG)

**Comment by kendramoroz** [comment] 2017-11-02 18:12
@JenHa thanks for sending this over! Are you experiencing this is in the extension or web app when creating Milestones? Is this occurring only in this one repo, or is it occurring across any other workspaces you're working in?

**Comment by JenHa** [comment] 2017-11-04 19:28
@kendramoroz 
I'm using the extension for chrome. 
I tried it in two different repositorities and both are showing the same error. 
But it's only when creating over the "boards" tab (click on the green + and then milestone, see on the picture above). 
It works to go to the "Issues" tab, then click on "milestones" and click here on "new milestone". Doing it this way shows no error and the new milestone appears. But here you can only choose an end date and must add the start date later when editing the milestone.

**Comment by hitochan777** [comment] 2017-11-05 11:57
@kendramoroz 
I am also experiencing this error in chrome extension.  In addition to what @JenHa mentions, I also encounter this error when creating over the "Reports>Burdown>Create new Milestone".

**Comment by kendramoroz** [comment] 2017-11-07 02:28
Thanks for following up! To help with next steps, would you be able to send over your timezone and a few times that work to setup a support debugging call? Based on your notes so far, the team and I would like to tackle a few scenarios and a support call will help ensure you're both setup for success quicker. Feel free to send over a few times directly to kendra@zenhub.com or post here and we'll get a calendar invite sent through!

**Comment by JenHa** [comment] 2017-11-07 12:10
Hello. 
My timezone is UTC+1. I have time every tuesday from 16:30 o'clock till 18:00 o'clock. 
Thursdays from 16:30 till 17:30 and most fridays from 9:00 till 10:30

**Comment by kendramoroz** [comment] 2017-11-07 22:10
Thanks for confirming, @JenHa! Based on the time differences, the best time to connect is 16:30 onwards. I'll send a calendar invite for next Tuesday between 16:30 and 18:00 with a Zoom URL we can both dial into. Looking forward to it!

**Comment by JenHa** [comment] 2017-11-08 11:45
For addition: 
I tried it in the web app now. Same error appears. 
Creating over "Reports>Burdown>Create new Milestone" like @hitochan777 said throws an error for me too (both in extension and web app).

**Comment by hitochan777** [comment] 2017-11-16 11:06
Could you please share the current status?

**Comment by kendramoroz** [comment] 2017-11-16 23:30
Hey @hitochan777 thanks for following up! We're working on debugging to reproduce the error! Would you be able to send through a few times to kendra@zenhub.com and your timezone so we can walkthrough this together to ensure there isn't anything unique about the error you're experiencing that we're missing?

**Comment by hitochan777** [comment] 2017-11-17 11:23
@kendramoroz I have sent you an email.

**Comment by kendramoroz** [comment] 2017-12-05 06:19
Adding context and closing this out for anyone else encountering this same issue! 

---

Looks like the problem occurs because the admin of the GitHub organization has turned on third party restrictions for oAuth applications and denied ZenHub access where it was once turned on. You can read more about third party restriction in this support article from GitHub: https://github.com/organizations/kendrastestorganization/settings/oauth_application_policy if you're unfamiliar with them.

![screen shot 2017-12-04 at 3 20 52 pm](https://user-images.githubusercontent.com/11036230/33592709-27b12576-d941-11e7-97bf-df074b86ebb1.png)


If you have the permissions to change this for your organization, you can click on the pencil in the organization oAuth settings and grant access to eliminate the problem. If you don’t have permissions, you’ll have to chat with your admin to grant access once more.

If anyone else encounters this error and permissions are granted, feel free to open a new Issue or comment here and we'll be sure to follow-up :)

**Closed by kendramoroz** 2017-12-05 06:19 UTC
Labels: ZenHub Support is Investigating!
