### ISSUE TITLE
Manage Organizations says: "You are not part of any organizations."

### ISSUE THREAD

**Issue by ziadsawalha** [ZenHubIO/support#207] opened 2015-03-19 13:45 UTC
And I cannot access my organizations' issues and boards
![screen shot 2015-03-19 at 2 43 07 pm](https://cloud.githubusercontent.com/assets/729918/6731619/60d56eba-ce46-11e4-8fd2-d098324bc8b7.png)

API call to `https://api.zenhub.io/v1/github/[my org]/[my repo]/access` to returns 400 and `{"message":"cannot find one Organization by shouldFindOne"}`

**Comment by azenMatt** [comment] 2015-03-19 16:02
Hi @ziadsawalha - we are looking into this now, il update you soon!

**Comment by ziadsawalha** [comment] 2015-03-19 18:07
Thanks!

**Comment by azenMatt** [comment] 2015-03-19 18:49
@ziadsawalha - we just push a fix for this, can you please re-try, it should be working now

**Comment by ziadsawalha** [comment] 2015-03-20 12:03
@azenMatt yes! Thanks, that works. What was it? Just a bug or did I do something unusual?

**Comment by azenMatt** [comment] 2015-03-20 17:42
Excellent. 

It was a bug on ourside (we are currently making lots of backend changes to get ready for #85 ), you were doing everything perfectly :+1:

**Closed by azenMatt** 2015-03-20 17:42 UTC

**Comment by milipili** [comment] 2015-07-11 09:20
The problem is still here actually....

**Comment by azenMatt** [comment] 2015-07-13 23:53
cc @aupright - can you give @milipili a hand?

**Comment by aupright** [comment] 2015-07-14 03:40
Hey @milipili - this sounds like it might be related to a permissions error with respect to third-party apps in GitHub. Can you help us test this by trying to following:

1) As an admin, navigate to your applications setting page here: https://github.com/settings/applications
2) Click on the ZenHub application, and in the application page, click the 'revoke access' button
3) Click on the ZenHub icon in your browser, sign in with GitHub, and click the 'authorize application'

Let me know if that does the trick!

**Comment by milipili** [comment] 2015-07-14 20:06
Ok it works now... thanks :)

**Comment by GeertHauwaerts** [comment] 2015-07-28 18:17
I have the same problem, when going to the ZenHub Dashboard, I receive the `You are not part of any organizations.` message.

I have already revoked all the access, authorized it again; all the permissions on `Personal Settings :: Applications` appear to be configured correctly.

![zenhub_access](https://cloud.githubusercontent.com/assets/7902071/8939491/00206990-3565-11e5-91ef-11a262d64a30.png)

* My account has ZenHub fully authorized
* Irssi organization has no restrictions on external tools (large opensource project)
* Thinfactory organization has ZenHub fully authorized
* My account is admin of both the Irssi & Thinfactory organizations

Do you guys have any idea on how to resolve the issue?

PS: I tried the auth/revoke/auth method on 2 different workstations.
