### ISSUE TITLE
Changing pipeline of different repo than current repo while viewing issue in board view doesn't change

### ISSUE THREAD

**Issue by gabrieljoelc** [ZenHubIO/support#416] opened 2015-10-21 20:21 UTC
The pipeline is not updated when I change the pipeline while view it in the board view. I have to go to the standard issue view to change it.

**Comment by jmcmurry** [comment] 2015-10-22 21:54
This doesn't seem related to https://github.com/ZenHubIO/support/issues/418, but please confirm.

**Comment by gabrieljoelc** [comment] 2015-10-22 22:11
I don't believe that's related. I can get to the board, but I can't change the Pipeline from an issue opened from a board.

**Comment by azenMatt** [comment] 2015-10-22 22:24
Hi @gabrieljoelc - I can recreate this - but only on multi-repo boards where the issue is part of a repo that was not the 'entry repo' (i.e, it is not the repo show at the top of the page) 


Is this the same for you, or is it all issues?

**Comment by gabrieljoelc** [comment] 2015-10-22 22:28
@azenMatt I didn't notice that distinction, but you are correct: it only happens when trying to change the Pipeline on issues from another repo than the one I'm currently on (when viewing a board with multiple repos).

**Comment by azenMatt** [comment] 2015-10-22 22:45
Ok - thats good news, we will have a fix live soon

**Comment by azenMatt** [comment] 2015-10-23 18:04
V2.10.5 is now live and has the fix for this!

**Closed by azenMatt** 2015-10-23 18:04 UTC
